tenant_id: "b41b72d0-4e9f-4c26-8a69-f949f367c91d"
client_id: "ca3b0207-fd51-4836-a3bc-fb4dba28afcf"
#client_secret_env: "SP_CHECKER_CLIENT_SECRET"

delegated_auth:
  token_cache_path: "~/.sp-checker-token-cache.json"   # where MSAL stores the refresh token

discovery:
  mode: "prefix"
  site_prefixes:
    - "EPAM SAP SE"

rules:
  leadership_folder_regex: "^Project SAP-[A-Za-z]+ leadership$"
  roaster_folder_name: "Roaster"

execution:
  max_parallel_sites: 4
  page_size: 200
  retry_attempts: 5
  retry_backoff_seconds: 2

reporting:
  output_dir: "./out"
  formats:
    - "json"
    - "csv"
    - "xlsx"
    - "html"
  only_failures_in_notification: false
  email:
    enabled: false
    recipients:
      - "pm@example.com"
    smtp_host: "smtp.office365.com"
    smtp_port: 587
    smtp_user_env: "SP_CHECKER_SMTP_USER"
    smtp_password_env: "SP_CHECKER_SMTP_PASSWORD"
    from_address: "noreply@example.com"
  teams:
    enabled: false
    webhook_env: "SP_CHECKER_TEAMS_WEBHOOK"
